[pytest]
# 1. Где искать тесты
testpaths = tests

# 2. Какие файлы считать тестами
python_files = test_*.py

# 3. Настройки асинхронности (важно для FastAPI 2026)
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session

# 4. Красивый и полезный вывод в консоль
# -v: подробнее, -s: показывать принты, -p no:warnings: убрать лишний мусор
addopts = -v -s -p no:warnings