"""о

Revision ID: 4e374833b80c
Revises: 
Create Date: 2026-03-29 19:33:35.381578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e374833b80c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SAVINGS', 'SPENDINGS', name='wallet_type'), nullable=False),
    sa.Column('init_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('init_balance', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_type', 'wallets', ['type'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StatsWalletTotal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('walletId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('income', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('limit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('StatsWalletTotal_pkey'))
    )
    op.create_index(op.f('StatsWalletTotal_walletId_key'), 'StatsWalletTotal', ['walletId'], unique=True)
    op.create_table('StatsDailyCategory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('walletId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('income', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('limit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['Category.id'], name=op.f('StatsDailyCategory_categoryId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('StatsDailyCategory_pkey'))
    )
    op.create_index(op.f('StatsDailyCategory_walletId_categoryId_date_key'), 'StatsDailyCategory', ['walletId', 'categoryId', 'date'], unique=True)
    op.create_table('Transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('INCOME', 'OUTCOME', name='TransactionType'), autoincrement=False, nullable=False),
    sa.Column('notation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('limit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('initDate', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('repeatTime', postgresql.ENUM('NEVER', 'EVERY_DAY', 'EVERY_MONTH', 'EVERY_YEAR', name='RepeatTimeType'), server_default=sa.text('\'NEVER\'::"RepeatTimeType"'), autoincrement=False, nullable=False),
    sa.Column('walletId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('linkedTransactionId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['Category.id'], name=op.f('Transaction_categoryId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['linkedTransactionId'], ['Transaction.id'], name=op.f('Transaction_linkedTransactionId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('Transaction_pkey'))
    )
    op.create_index(op.f('Transaction_walletId_idx'), 'Transaction', ['walletId'], unique=False)
    op.create_index(op.f('Transaction_type_idx'), 'Transaction', ['type'], unique=False)
    op.create_index(op.f('Transaction_categoryId_idx'), 'Transaction', ['categoryId'], unique=False)
    op.create_table('Category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('initDate', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('walletId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Category_pkey'))
    )
    op.drop_index('ix_wallet_type', table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
