fake_products_db = [
    {
        "id": 1,
        "name": "iPhone 15 Pro",
        "price": 999,
        "category": "phones",
        "in_stock": True,
    },
    {
        "id": 2,
        "name": "MacBook Pro 14",
        "price": 1999,
        "category": "laptops",
        "in_stock": True,
    },
    {
        "id": 3,
        "name": "AirPods Pro",
        "price": 249,
        "category": "accessories",
        "in_stock": False,
    },
    {
        "id": 4,
        "name": "iPad Air",
        "price": 599,
        "category": "tablets",
        "in_stock": True,
    },
    {
        "id": 5,
        "name": "Samsung Galaxy S24",
        "price": 899,
        "category": "phones",
        "in_stock": True,
    },
    {
        "id": 6,
        "name": "Dell XPS 15",
        "price": 1799,
        "category": "laptops",
        "in_stock": True,
    },
    {
        "id": 7,
        "name": "Logitech MX Master 3",
        "price": 99,
        "category": "accessories",
        "in_stock": True,
    },
    {
        "id": 8,
        "name": "PlayStation 5",
        "price": 499,
        "category": "gaming",
        "in_stock": False,
    },
    {
        "id": 9,
        "name": "Xbox Series X",
        "price": 499,
        "category": "gaming",
        "in_stock": True,
    },
    {
        "id": 10,
        "name": "Apple Watch Series 9",
        "price": 399,
        "category": "wearables",
        "in_stock": True,
    },
    {
        "id": 11,
        "name": "Apple1 Watch Series 9",
        "price": 450,
        "category": "wearables",
        "in_stock": True,
    },
    {
        "id": 12,
        "name": "Apple2 Watch Series 9",
        "price": 700,
        "category": "wearables",
        "in_stock": True,
    },
]
